agent_type: "GPPO"

agent_params:
    memory_size: 512
    batch_size: 512
    learning_rate: 0.001676731266507171
    n_epochs: 5
    gamma: 0.999
    gae_lambda: 0.9366093624383212
    clip_range: 0.3247192026115954
    clip_range_vf: null         # corresponds to Optional[float] = None
    ent_coef: 0.000585045
    vf_coef: 0.2719126203097403
    max_grad_norm: 0.7942051282152534
    num_inducing_points: 128
    num_quad_sites: 8
    beta: 0.5 # 0.825162386521697
    sample_vf: True,
    hidden_layers_config:
        - output_dims: 6 # 1 # 6
          mean_type: "linear"
    policy_hidden_config:
        - output_dims: 6 # null # 6
          mean_type: "constant"
    value_hidden_config:
        - output_dims: null
          mean_type: "constant"