agent_type: "GPPO"

agent_params:
    n_steps: 512
    batch_size: 512
    learning_rate: 0.002913
    n_epochs: 8
    gamma: 0.999
    gae_lambda: 0.9
    clip_range: 0.1
    clip_range_vf: null         # corresponds to Optional[float] = None
    ent_coef: 0.0
    vf_coef: 0.73973
    max_grad_norm: 0.425093
    num_inducing_points: 128
    num_quad_sites: 8
    beta: 0.5 # 0.825162386521697
    sample_vf: True,
    hidden_layers_config:
        - output_dims: 6 # 1 # 6
          mean_type: "linear"
    policy_hidden_config:
        - output_dims: 6 # null # 6
          mean_type: "constant"
    value_hidden_config:
        - output_dims: null
          mean_type: "constant"
