agent_type: "GPPO"

agent_params:
    n_steps: 249
    batch_size: 256
    learning_rate: 0.001949
    n_epochs: 10
    gamma: 0.95
    gae_lambda: 0.9
    clip_range: 0.347822
    clip_range_vf: null
    ent_coef: 8.7e-05
    vf_coef: 0.918695
    max_grad_norm: 0.869612
    num_inducing_points: 128
    num_quad_sites: 8
    beta: 0.5
    sample_vf: True
    hidden_layers_config:
        - output_dims: 17
          mean_type: "linear"
    policy_hidden_config:
        - output_dims: 17
          mean_type: "constant"
    value_hidden_config:
        - output_dims: null
          mean_type: "constant"
