agent_type: "GPPO"

agent_params:
    memory_size: 32
    batch_size: 64
    learning_rate: 0.00200222425
    n_epochs: 5
    gamma: 0.999
    gae_lambda: 0.9
    clip_range: 0.4
    clip_range_vf: null         # corresponds to Optional[float] = None
    ent_coef: 1.37976e-04
    vf_coef: 0.19816
    max_grad_norm: 0.3
    num_inducing_points: 256
    num_quad_sites: 8
    beta: 0.5 # 0.825162386521697
    sample_vf: True,
    hidden_layers_config:
        - output_dims: 1 # 1 # 6
          mean_type: "linear"
    policy_hidden_config:
        - output_dims: null # null # 6
          mean_type: "constant"
    value_hidden_config:
        - output_dims: null
          mean_type: "constant"