agent_type: "GPPO"

agent_params:
    n_steps: 256
    batch_size: 512
    learning_rate: 0.005751
    n_epochs: 9
    gamma: 0.999
    gae_lambda: 0.9
    clip_range: 0.350164
    clip_range_vf: null
    ent_coef: 0.001684
    vf_coef: 0.835695
    max_grad_norm: 0.664338
    num_inducing_points: 128
    num_quad_sites: 8
    beta: 0.5
    sample_vf: True
    hidden_layers_config:
        - output_dims: 6
          mean_type: "linear"
    policy_hidden_config:
        - output_dims: 6
          mean_type: "constant"
    value_hidden_config:
        - output_dims: null
          mean_type: "constant"
