agent_type: "PPO"

agent_params:
    memory_size: 32
    batch_size: 64
    learning_rate: 0.000222425
    n_epochs: 5
    gamma: 0.999
    gae_lambda: 0.9
    clip_range: 0.4
    clip_range_vf: null         # corresponds to Optional[float] = None
    ent_coef:  1.37976e-07
    vf_coef: 0.19816
    max_grad_norm: 0.3