agent_type: "SB_PPO"

agent_params:
  n_steps: 512
  batch_size: 32
  learning_rate: 1.90609e-05
  n_epochs: 10
  gamma: 0.98
  gae_lambda: 0.8
  clip_range: 0.1
  clip_range_vf: null
  ent_coef: 4.9646e-07
  vf_coef: 0.677239
  max_grad_norm: 0.6
  # n_envs: 1
  # n_timesteps: !!float 1e7
  # policy_kwargs:
  #   net_arch:
  #     - pi: [256, 256]
  #       vf: [256, 256]
  #   activation_fn: "relu"
  #   ortho_init: false
  #   log_std_init: -2
