agent_type: "SB_PPO"

agent_params:
  n_steps: 512
  batch_size: 32
  learning_rate: 5.05041e-05
  n_epochs: 20
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  ent_coef: 0.000585045
  vf_coef: 0.871923
  max_grad_norm: 1
  # policy_kwargs:
  #   net_arch:
  #     - pi: [64, 64]
  #       vf: [64, 64]
  #  activation_fn: "tanh"
