name: train

train: True
load_model: False
save_model: False
model_path: "../models"   # e.g., /models/gppo/file.pth
import_metrics: True
export_metrics: True
# List of agents to import/enable
agents:
  - GPPO
  - SB_PPO

normalize_obs: True
clip_obs: 10.0 #1.0   #
